/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ChildElement {}
  interface ParentElement {}
}

declare global {


  interface HTMLChildElementElement extends Components.ChildElement, HTMLStencilElement {}
  var HTMLChildElementElement: {
    prototype: HTMLChildElementElement;
    new (): HTMLChildElementElement;
  };

  interface HTMLParentElementElement extends Components.ParentElement, HTMLStencilElement {}
  var HTMLParentElementElement: {
    prototype: HTMLParentElementElement;
    new (): HTMLParentElementElement;
  };
  interface HTMLElementTagNameMap {
    'child-element': HTMLChildElementElement;
    'parent-element': HTMLParentElementElement;
  }
}

declare namespace LocalJSX {
  interface ChildElement {}
  interface ParentElement {}

  interface IntrinsicElements {
    'child-element': ChildElement;
    'parent-element': ParentElement;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'child-element': LocalJSX.ChildElement & JSXBase.HTMLAttributes<HTMLChildElementElement>;
      'parent-element': LocalJSX.ParentElement & JSXBase.HTMLAttributes<HTMLParentElementElement>;
    }
  }
}


